agents:
    trae_agent:
        enable_lakeview: true
        model: trae_agent_model
        max_steps: 200
        tools:
            - bash
            - str_replace_based_edit_tool
            - sequentialthinking
            - task_done
allow_mcp_servers:
    - TestSprite
mcp_servers:
    TestSprite:
      command: npx
      args:
        - "@testsprite/testsprite-mcp@latest"
      env:
        API_KEY: 
lakeview:
    model: lakeview_model

model_providers:
    openai:
        api_key: 
        provider: openai

models:
    trae_agent_model:
        model_provider: openai
        model: gpt-4o
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
    lakeview_model:
        model_provider: anthropic
        model: claude-3.5-sonnet
        max_tokens: 4096
        temperature: 0.5
        top_p: 1
        top_k: 0
        max_retries: 10
        parallel_tool_calls: true
